### ISSUE TITLE
A small, annoying error

### ISSUE THREAD

**Issue by GAP68** [jamesshore/object_playground#6]
jake aborted.
Error: Incorrect Node version. Expected exactly [v0.10.32], but was [v4.2.2].
    at api.fail (object_playground\node_modules\jake\lib\api.js:326:18)
    at failWithQualifier (object_playground\build\util\version_checker.js:7:4)
    at Object.exports.check (object_playground\build\util\version_checker.js:16:5)
    at null.action (objectplayground\object_playground\Jakefile.js:58:11)
    at TaskBase.run (object_playground\node_modules\jake\lib\task\task.js:199:27)
    at TaskBase.runPrereqs (object_playground\node_modules\jake\lib\task\task.js:119:12)
    at TaskBase.invoke (object_playground\node_modules\jake\lib\task\task.js:99:10)
    at TaskBase.nextPrereq (object_playground\node_modules\jake\lib\task\task.js:151:23)
    at TaskBase.runPrereqs (object_playground\node_modules\jake\lib\task\task.js:116:12)
    at TaskBase.invoke (\object_playground\node_modules\jake\lib\task\task.js:99:10)

**Comment by jamesshore** [comment]
That's intentional. The build has only been confirmed to work on 0.10.32.

You can suppress the error by passing `loose=true` as an option to Jake.

**Comment by GAP68** [comment]
Thanks, it helped
